### PR TITLE
MECFSDEV-1750 require password reset for all users feature

### PR DESCRIPTION
**Pull request by mavocado4**
You can run the following to set all non-admin users to be required to reset their password:
```
docker exec -t mecfs_ckan bash -c "ckan advancedauth reset-password"
```
The following will work for any user including sysadmins:
```
docker exec -it mecfs_ckan bash -c "ckan advancedauth reset-password --username=<username>
```

Upon login and on subsequent routes, the user will be redirected to the `/user/required_reset/<id>` page. This page is derived from the edit_user_form.html template with all other fields stripped out except for the password fields.

One major revision is that originally I had intercepted only when the user logs in, but now it intercepts on all routes except for those listed in the middleware overrides attribute. It seems to work fine without much of a performance issue since we have a small table for users, but I think staging will be a better indicator.

Note: since I extended the perform reset view (to update the post method to set the reset field in the db), I went ahead and used the error_summary to fix https://jira.rti.org/browse/MECFSDEV-1753

### CODE REVIEW

**Comment by rjruizes** [comment]
As discussed in meeting, required reset should trigger email, so that the user's email serves as MFA in this event

**Comment by rjruizes** [comment]
Sorry for the delay in reviewing this. I just tried it out.

1. Open Chrome, go to http://localhost:5001
2. Create new user, dummyuser
3. Trigger reset via CLI
4. dummyuser now prompted to reset password ✅
5. Enter in alternate email. Alternate email never gets reset email. I guess this is good.
6. Use username, dummyuser. dummyuser gets email from sendgrid ✅
7. Click link from my email (sendgrid encoded the URL unfortunately) from another browser, Safari. I'm prompted to login. I'm confused- is this resetting my password? No, it wants my original password to reset my password ❌

**Comment by mavocado4** [comment]
@rjruizes I'm currently stuck on step 6 where my ckan container crashes while waiting for the email to be sent. Any ideas what could have changed? I did a clean build and no errors in the logs:
```
mecfs_ckan            | 2024-06-27 20:21:28,629 INFO  [ckan.config.middleware.flask_app:406]  200 /user/reset render time 0.346 seconds
mecfs_ckan            | 2024-06-27 20:21:30,718 INFO  [ckan.views.user:613] Password reset requested for user "malvarado"
mecfs_ckan            | 2024-06-27 20:21:30,747 INFO  [ckan.views.user:654] Emailing reset link to user: malvarado
mecfs_ckan            | Thu Jun 27 20:23:31 2024 - *** HARAKIRI ON WORKER 1 (pid: 705, try: 1) ***
```

**Comment by rjruizes** [comment]
No, idk. That isn't an error I've gotten before.

**Comment by mavocado4** [comment]
@rjruizes Could you confirm you need to be logged in to reset the password? It might be something I need to investigate and reproduce but I'd like to confirm it first. I tried from Safari and Chrome and was able to reset the password without needing to be logged in. Sorry to bother you about starting up mapmecfs again just to double check, I know it's annoying
Screenshot 2024-07-01 at 12 08 32 PM

**Comment by mavocado4** [comment]
I plan to push `ckan.site_title=mapMECFS` to mapmecfs main branch for email typo fix

**Comment by rjruizes** [comment]
Just retested and it works as expected.

**Pull request merged**
